language: python
sudo: false

cache:
  pip: true
  directories:
    - $HOME/buildout-cache

before_install:
    - mkdir -p $HOME/buildout-cache/{downloads,eggs,extends}
    - mkdir $HOME/.buildout
    - echo "[buildout]" > $HOME/.buildout/default.cfg
    - echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
    - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg
    - echo "extends-cache = $HOME/buildout-cache/extends" >> $HOME/.buildout/default.cfg
    - echo "abi-tag-eggs = true" >> $HOME/.buildout/default.cfg


matrix:
    include:
        - python: "2.7"
          env: TOXENV=py27
        - python: "3.4"
          env: TOXENV=py34
        - python: "3.5"
          env: TOXENV=py35
        - python: "3.6"
          env: TOXENV=py36
        - python: "pypy"
          env: TOXENV=pypy
        - python: "2.7"
          env: TOXENV=flake8,isort
        - python: "3.6"
          env: TOXENV=flake8,isort

install:
    - travis_retry pip install -U setuptools==33.1.1 tox coveralls coverage

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
    - travis_retry tox

after_success:
    - coverage combine
    - coveralls

after_script:
  - sh -e /etc/init.d/xvfb stop

notifications:
  email:
    - travis-reports@plone.com
