language: python
python:
  - 2.7

install:
  - python bootstrap-buildout.py --setuptools-version=8.3
  - bin/buildout

script:
  - bin/code-analysis
  - bin/nosetests
  - bin/mrbob -O collective.foo --config test_answers.ini ./bobtemplates/plone_addon
  - bin/test

notifications:
  email:
    - travis-reports@plone.com
