language: python
python:
  - 2.7

install:
  - python bootstrap-buildout.py --setuptools-version=8.3
  - bin/buildout

script:
#  - bin/nosetests
#  - bin/mrbob -O collective.foo --config test_answers.ini ./bobtemplates/plone_addon
#  - bin/mrbob -O collective.foo.bar --config test_answers_nested.ini ./bobtemplates/plone_addon_nested
  - cat bin/test
  - bin/test

notifications:
  email:
    - travis-reports@plone.com
