language: python
python:
  - 2.7
sudo: false
cache:
  directories:
  - test.plone_addon/eggs

install:
  - python bootstrap-buildout.py --setuptools-version=8.3
  - bin/buildout

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - bin/code-analysis
  - bin/nosetests
  - bin/test

notifications:
  email:
    - travis-reports@plone.com
